### ISSUE TITLE
Dashboard isn't accessible

### ISSUE THREAD

**Issue by coolpalani** [techjw/k8s-gcp#1] opened 2018-04-28 12:42 UTC
I have deployed the k8s cluster using your procedure.
I am trying to access the kubernetes dashboard using `./kismatic dashboard`

But dashboard isn't showing.

Error: 'dial tcp 172.16.251.195:8443: getsockopt: connection timed out'
Trying to reach: 'https://172.16.251.195:8443/'

**Comment by techjw** [comment] 2018-04-30 19:36
I have PR that I will be merging in to fix some bugs, one which likely is the cause (lack of allowed IPIP traffic for Calico within the kubernetes network).

You can try adding `ipip` to the list of protocols (no port) defined on the deployment's `*-network-allow-internal` firewall rule to see if that fixes the issue for your current setup.

*Update:* PR #2 merged

**Comment by coolpalani** [comment] 2018-05-01 07:45
Thank you very much for take this as priority and fixed it. (Including dashboards and make file commands)
I am trying to provision persistence storage after storage class added, but it's not succeed.
`[root@localhost ~]# kubectl get pvc`
`NAME        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE`
`my-volume   Pending                                       faster         1m`

[https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses](url)

`kubectl apply -f ssd-storageclass.yaml`
`kubectl apply -f ssd-claim.yaml`

Is it possible to provision dynamic volume only if we are using GKE.

in self hosted k8s cluster method, do we want to manually create as described in below url
[https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk](url)

`Creating a PD`

`Before you can use a GCE PD with a pod, you need to create it.`

`gcloud compute disks create --size=20GB --zone=us-central1-a my-data-disk`

Then we have to define PD details in our POD deployment file
Example pod

apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4

**Comment by techjw** [comment] 2018-05-01 12:50
You can get automatic provisioning of storage in GCE with a Kubernetes cluster that is not the GKE service, but it requires enabling the cloud provider (`--cloud-provider gce`) and then defining your PV/PVC to use the GCE storage class. I haven't had time to test the cloud-provider setup.

For now, I'm closing this issue as resolved from code improvements in PR #2

**Closed as completed by techjw** 2018-05-01 12:50 UTC
